[project]
name = "langchain"
version = "0.1.0"
description = "Tutorial for langchain"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "grandalf>=0.8",
    "pydantic[email]>=2.11.7",
]
